fieldLayouts:
  8fb7ff53-cceb-404f-bc2f-ae34ee6a94f7:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 5de6ddfc-7e58-4e67-98da-108a0a3cb14a
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: f900aa5e-c80c-4d73-876a-d45c0708f0c5 # Solution Main Title
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 154e3ff0-9b1e-4e90-b187-e38fd90aaf29
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: c4a611b6-b197-454c-8b52-9a6b973cfd35 # Solution Main Subheading
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: af1dd0c8-26e5-4c1c-83ea-bd2cf84e4f78
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 0c2f4fef-9935-4d4a-9677-0e4c034882a0 # Logo
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 838aa4b1-5291-4a8b-a689-05b8d24bebd6
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 61282942-49f6-443d-a5e0-8d927401ede5 # Logo Strip
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: f4a6a091-3346-4962-8e60-d1a4d72bfd1a
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 8fca0acb-dd63-4436-8081-de833c915885
        userCondition: null
handle: homePage
hasTitleField: false
name: 'Home Page'
section: 555e190a-6d35-423b-89be-d0e492f5bc58 # Home Page
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
sortOrder: 1
titleFormat: '{section.name|raw}'
titleTranslationKeyFormat: null
titleTranslationMethod: site
