fieldLayouts:
  8fb7ff53-cceb-404f-bc2f-ae34ee6a94f7:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: da5f037a-2657-4158-a31e-5b982b3132e8 # Hero Title Text
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 04e5c6f8-fb80-42eb-9345-5d2523f51f80
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 5e783436-9213-4fd9-acc2-4703d88a20dd # Hero Subtext
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 9d33372b-b389-437e-a2de-5b647f5f0f06
            userCondition: null
            warning: null
            width: 100
        name: Hero
        uid: 210d611b-667c-4d6a-ad94-c978465ae69b
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 94a78850-d37f-4f2e-9b70-88b0b065cea4 # Logos
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 05cec254-7955-4a9b-b3f2-3f90f52bba45
            userCondition: null
            warning: null
            width: 100
        name: Logos
        uid: 4e1220bc-2b1e-4ccc-9fc6-c2f1c1763f5b
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: f900aa5e-c80c-4d73-876a-d45c0708f0c5 # Solutions Main Title
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 154e3ff0-9b1e-4e90-b187-e38fd90aaf29
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: c4a611b6-b197-454c-8b52-9a6b973cfd35 # Solutions Main Subheading
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: af1dd0c8-26e5-4c1c-83ea-bd2cf84e4f78
            userCondition: null
            warning: null
            width: 100
        name: 'Solutions Headings Text'
        uid: 3f69fe52-fb0f-40d2-b7e8-7c4ecb3d9df3
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 8f093e2b-d23f-4153-9831-0b2ee58d75d7 # Solution Matrix
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 12fa6089-2664-4eaa-bf73-0d34fc9077a6
            userCondition: null
            warning: null
            width: 100
        name: 'Solution Cards'
        uid: f82d88c7-ab05-4744-9790-5366026e151a
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 5de6ddfc-7e58-4e67-98da-108a0a3cb14a
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 8fca0acb-dd63-4436-8081-de833c915885
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 1dde08a7-0369-4bcb-97b7-6b4f05210441 # Tabs Panel1 Name
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 17322555-93e6-41ed-9ab4-d510b76b653a
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: fa2788f2-0a27-402c-8992-ee89a969b7ba # Tabs Panel1 Title
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 5a07b60a-2714-4180-a1cd-9baa72d3f053
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 0cf72060-b216-4306-99c9-419e533ec7d6 # Tabs Panel1 Subheading
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 474c2aa1-2f53-4454-bec8-a6ecb51a8534
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: d2a8a211-1516-4364-83cc-15b8e12d70b3 # Tabs Panel1 Bulletpoint Text1
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 1dc77211-36ec-4b0a-a7d3-d396f49e52f3
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 5c21f109-0825-4f19-b7f9-4fb32f04d4b2 # Tabs Panel1 Bulletpoint Text2
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: cbd944d8-04c0-463c-a700-15ff61d8dff9
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 010d4606-43a0-4cbb-9e7e-6940170f0e06 # Tabs Panel1 Bulletpoint Text3
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: a2acde32-efa8-4adb-b27d-e63328dbed1d
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: ac8660a2-90e9-4864-90ca-2f340ffe007f # Tabs Panel1 Button Text
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 876a2fda-ee53-4659-9a95-c6acafee864c
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 492d9a19-dc4e-4993-a783-e6f60b0a5dba # Tabs Panel1 Link Text
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 54cd4f8f-55e9-4be5-9769-aee5b9201bff
            userCondition: null
            warning: null
            width: 100
        name: 'Tabs Panel1'
        uid: 9912c222-6c9f-45dc-85c2-73da02426739
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 0b3e671b-1f0d-4f06-8286-6c4b33e03cac # Tabs Panel2 Name
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 22b3352d-6e6e-4020-a4ca-0f98add224b5
            userCondition: null
            warning: null
            width: 100
        name: 'Tabs Panel2'
        uid: 92ee41e6-4ad6-4225-bde1-02ebde93ec62
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 5255f582-4244-425b-a88f-3d2d8f2b05fe # Tabs Panel3 Name
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 23008822-35ac-4dc5-8f95-93ea289bf8c2
            userCondition: null
            warning: null
            width: 100
        name: 'Tabs Panel3'
        uid: db4c8e82-bf1e-4551-bd2d-02683d378318
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 3cc5cbc2-41db-4b32-92dc-fb441c4b56f4 # Tabs Panel4 Name
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: aaf1037b-40ac-4bd4-86e9-a24ba4a289e3
            userCondition: null
            warning: null
            width: 100
        name: 'Tabs Panel 4'
        uid: 420676d6-c96d-42d3-bf02-ce53b32f7307
        userCondition: null
handle: homePage
hasTitleField: false
name: 'Home Page'
section: 555e190a-6d35-423b-89be-d0e492f5bc58 # Home Page
showStatusField: false
slugTranslationKeyFormat: null
slugTranslationMethod: site
sortOrder: 1
titleFormat: '{section.name|raw}'
titleTranslationKeyFormat: null
titleTranslationMethod: site
