columnSuffix: ypiwrzlk
contentColumnType: text
fieldGroup: 4076ab59-327c-42ee-99c4-826bfedf430e # Hero
handle: heroSubtext
instructions: null
name: 'Hero Subtext'
searchable: false
settings:
  byteLimit: null
  charLimit: null
  code: false
  columnType: null
  initialRows: 4
  multiline: false
  placeholder: null
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
