columnSuffix: null
contentColumnType: string
fieldGroup: c4fc1131-0ef6-450b-8aaf-3b49b261f51d # Branding
handle: logoStrip
instructions: 'Add media categories to a logo to have that logo displayed in that category''s grid'
name: 'Logo Strip'
searchable: false
settings:
  contentTable: '{{%matrixcontent_logostrip}}'
  maxBlocks: null
  minBlocks: null
  propagationKeyFormat: null
  propagationMethod: all
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
