columnSuffix: null
contentColumnType: string
fieldGroup: 02aea2db-7a51-4c6f-a146-c2123960fe5d # Navigation
handle: navLinks
instructions: null
name: 'Nav Links'
searchable: false
settings:
  contentTable: '{{%matrixcontent_navlinks}}'
  maxBlocks: null
  minBlocks: null
  propagationKeyFormat: null
  propagationMethod: all
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
