columnSuffix: null
contentColumnType: string
fieldGroup: 50e3b3bb-a6f6-4870-a4d1-d3c78f1e48ba # Logo Strip
handle: sitesettingmatrix
instructions: 'Add the number of logos you would like to show on the grid at each breakpoint'
name: siteSettingMatrix
searchable: false
settings:
  contentTable: '{{%matrixcontent_sitesettingmatrix}}'
  maxBlocks: null
  minBlocks: null
  propagationKeyFormat: null
  propagationMethod: all
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
