columnSuffix: gxuxvtek
contentColumnType: string(60)
fieldGroup: 93d458fd-c496-457f-aa0e-f73f4c7ff0ea # Solutions
handle: solutionsCard3LinkText
instructions: 'Link text for Solutions Card 3'
name: 'Solutions Card3 Link Text'
searchable: false
settings:
  byteLimit: null
  charLimit: 15
  code: false
  columnType: null
  initialRows: 4
  multiline: false
  placeholder: null
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
