columnSuffix: rzumpvrb
contentColumnType: text
fieldGroup: 93d458fd-c496-457f-aa0e-f73f4c7ff0ea # Solutions
handle: solutionsButtonText
instructions: 'The text that goes on the solutions CTA button'
name: 'Solutions Button Text'
searchable: false
settings:
  availableTransforms: ''
  availableVolumes: '*'
  columnType: text
  configSelectionMode: choose
  defaultTransform: ''
  manualConfig: ''
  purifierConfig: null
  purifyHtml: true
  redactorConfig: null
  removeEmptyTags: false
  removeInlineStyles: false
  removeNbsp: false
  showHtmlButtonForNonAdmins: true
  showUnpermittedFiles: false
  showUnpermittedVolumes: false
  uiMode: enlarged
translationKeyFormat: null
translationMethod: none
type: craft\redactor\Field
