columnSuffix: uaypaitv
contentColumnType: char(7)
fieldGroup: 93d458fd-c496-457f-aa0e-f73f4c7ff0ea # Solutions
handle: solutionsCard2ButtonColor
instructions: 'The colour for the CTA button on Solutions Card2'
name: 'Solutions Card2 Button Color'
searchable: false
settings:
  defaultColor: '#f26839'
translationKeyFormat: null
translationMethod: none
type: craft\fields\Color
