columnSuffix: bshijbtm
contentColumnType: string(60)
fieldGroup: 93d458fd-c496-457f-aa0e-f73f4c7ff0ea # Solutions
handle: solutionsCard1LinkText
instructions: 'Text for the link on Card1'
name: 'Solutions Card1 Link Text'
searchable: false
settings:
  byteLimit: null
  charLimit: 15
  code: false
  columnType: null
  initialRows: 4
  multiline: false
  placeholder: 'Request a Demo'
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
