columnSuffix: plnlphfr
contentColumnType: char(7)
fieldGroup: 93d458fd-c496-457f-aa0e-f73f4c7ff0ea # Solutions
handle: solutionsCard3Color
instructions: 'Background colour for Solutions Card3'
name: 'Solutions Card3 Color'
searchable: false
settings:
  defaultColor: '#ceece0'
translationKeyFormat: null
translationMethod: none
type: craft\fields\Color
