columnSuffix: tqfasffy
contentColumnType: char(7)
fieldGroup: 93d458fd-c496-457f-aa0e-f73f4c7ff0ea # Solutions
handle: solutionCardColor
instructions: 'The background colour for the card'
name: 'Solution Card Color'
searchable: false
settings:
  defaultColor: '#ffffff'
translationKeyFormat: null
translationMethod: none
type: craft\fields\Color
