columnSuffix: syofpcrd
contentColumnType: text
fieldGroup: 93d458fd-c496-457f-aa0e-f73f4c7ff0ea # Solutions
handle: solutionsCard1BulletpointText3
instructions: null
name: 'Solutions Card1 Bulletpoint Text3'
searchable: false
settings:
  byteLimit: null
  charLimit: null
  code: false
  columnType: null
  initialRows: 4
  multiline: false
  placeholder: null
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
