columnSuffix: fhlcinzn
contentColumnType: text
fieldGroup: 93d458fd-c496-457f-aa0e-f73f4c7ff0ea # Solutions
handle: solutionsCard2Subheading
instructions: 'Subheading paragraph for Solutions Card2'
name: 'Solutions Card2 Subheading'
searchable: false
settings:
  byteLimit: null
  charLimit: null
  code: false
  columnType: null
  initialRows: 4
  multiline: false
  placeholder: null
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
