columnSuffix: cwdehpwd
contentColumnType: char(7)
fieldGroup: 93d458fd-c496-457f-aa0e-f73f4c7ff0ea # Solutions
handle: solutionsCard2Color
instructions: 'Background colour for Solutions card 2'
name: 'Solutions Card2 Color'
searchable: false
settings:
  defaultColor: '#ded1de'
translationKeyFormat: null
translationMethod: none
type: craft\fields\Color
