columnSuffix: kjhmpftl
contentColumnType: char(7)
fieldGroup: 93d458fd-c496-457f-aa0e-f73f4c7ff0ea # Solutions
handle: solutionsCard3ButtonColor
instructions: 'CTA Button colour for Solutions Card 3'
name: 'Solutions Card3 Button Color'
searchable: false
settings:
  defaultColor: '#f26839'
translationKeyFormat: null
translationMethod: none
type: craft\fields\Color
