columnSuffix: lngutsev
contentColumnType: text
fieldGroup: 4aa35177-3ee6-45b7-9fbb-0dbc64d50bcc # Tabs
handle: tabsPanel1BulletpointText3
instructions: 'Bulletpoint3 text for tab panel 1'
name: 'Tabs Panel1 Bulletpoint Text3'
searchable: false
settings:
  byteLimit: null
  charLimit: null
  code: false
  columnType: null
  initialRows: 4
  multiline: false
  placeholder: null
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
