columnSuffix: nsxzcnmr
contentColumnType: text
fieldGroup: 4aa35177-3ee6-45b7-9fbb-0dbc64d50bcc # Tabs
handle: tabsPanel1Name
instructions: 'Name and ID for Panel 1'
name: 'Tabs Panel1 Name'
searchable: false
settings:
  byteLimit: null
  charLimit: null
  code: false
  columnType: null
  initialRows: 4
  multiline: false
  placeholder: null
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
