columnSuffix: rsgxgeuo
contentColumnType: string(60)
fieldGroup: 4aa35177-3ee6-45b7-9fbb-0dbc64d50bcc # Tabs
handle: tabsPanel1ButtonText
instructions: 'Button text for tabs panel 1'
name: 'Tabs Panel1 Button Text'
searchable: false
settings:
  byteLimit: null
  charLimit: 15
  code: false
  columnType: null
  initialRows: 4
  multiline: false
  placeholder: null
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
