columnSuffix: eqjapjys
contentColumnType: text
fieldGroup: 4aa35177-3ee6-45b7-9fbb-0dbc64d50bcc # Tabs
handle: tabtitlemain
instructions: 'Main title for the tab section'
name: TabTitleMain
searchable: false
settings:
  byteLimit: null
  charLimit: null
  code: false
  columnType: null
  initialRows: 4
  multiline: false
  placeholder: null
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
