dateModified: 1703222414
elementSources:
  craft\elements\Asset:
    -
      defaultSort:
        - dateCreated
        - desc
      disabled: false
      key: 'volume:bb0e0fd9-19d2-405c-a25b-72cf038c254e' # Images
      tableAttributes:
        - filename
        - size
        - dateModified
        - link
        - kind
        - imageSize
        - width
        - height
        - alt
        - id
      type: native
    -
      key: 'folder:9dbfce8d-97e5-4716-9225-bdf56638d832'
      type: native
email:
  fromEmail: alunprice089@gmail.com
  fromName: ektask
  transportType: craft\mail\transportadapters\Sendmail
fs:
  hardDisk:
    hasUrls: true
    name: 'Hard Disk'
    settings:
      path: '@webroot/static/images'
    type: craft\fs\Local
    url: '@web/static/images'
meta:
  __names__:
    0b3e671b-1f0d-4f06-8286-6c4b33e03cac: 'Tabs Panel2 Name' # Tabs Panel2 Name
    0b4ecdc7-9211-4ea6-9185-2b85f5bc627a: 'Sol Link Text' # Sol Link Text
    0cf72060-b216-4306-99c9-419e533ec7d6: 'Tabs Panel1 Subheading' # Tabs Panel1 Subheading
    1dde08a7-0369-4bcb-97b7-6b4f05210441: 'Tabs Panel1 Name' # Tabs Panel1 Name
    02aea2db-7a51-4c6f-a146-c2123960fe5d: Navigation # Navigation
    3cc5cbc2-41db-4b32-92dc-fb441c4b56f4: 'Tabs Panel4 Name' # Tabs Panel4 Name
    4aa35177-3ee6-45b7-9fbb-0dbc64d50bcc: Tabs # Tabs
    5c21f109-0825-4f19-b7f9-4fb32f04d4b2: 'Tabs Panel1 Bulletpoint Text2' # Tabs Panel1 Bulletpoint Text2
    5e783436-9213-4fd9-acc2-4703d88a20dd: 'Hero Subtext' # Hero Subtext
    8f093e2b-d23f-4153-9831-0b2ee58d75d7: 'Solution Matrix' # Solution Matrix
    9ec84187-5842-4b64-a363-df2809790092: 'Sol Bulletpoint Text 1' # Sol Bulletpoint Text 1
    010d4606-43a0-4cbb-9e7e-6940170f0e06: 'Tabs Panel1 Bulletpoint Text3' # Tabs Panel1 Bulletpoint Text3
    12dae174-ac60-45df-8001-7bd40dedce57: 'Solutions Global' # Solutions Global
    15e796fd-d9f9-4eb9-900b-19e85ab478a8: Logos # Logos
    50da8cdf-9a5c-4c56-83fe-94dca5ddd3fe: TabTitleMain # TabTitleMain
    50e3b3bb-a6f6-4870-a4d1-d3c78f1e48ba: 'Logo Strip' # Logo Strip
    93d458fd-c496-457f-aa0e-f73f4c7ff0ea: Solutions # Solutions
    94a78850-d37f-4f2e-9b70-88b0b065cea4: Logos # Logos
    417edd7f-d132-4e0f-804f-1539f9b27356: solCardTitle # solCardTitle
    492d9a19-dc4e-4993-a783-e6f60b0a5dba: 'Tabs Panel1 Link Text' # Tabs Panel1 Link Text
    555e190a-6d35-423b-89be-d0e492f5bc58: 'Home Page' # Home Page
    3192af92-0e16-402a-bc85-8ec22b259c0b: 'Link Text' # Link Text
    4076ab59-327c-42ee-99c4-826bfedf430e: Hero # Hero
    5255f582-4244-425b-a88f-3d2d8f2b05fe: 'Tabs Panel3 Name' # Tabs Panel3 Name
    8200bbfd-113b-4164-b60a-f5a5a1c15c32: ektask # ektask
    9508eea7-9b70-4558-8d1a-d1f02642b58d: 'Sol Bulletpoint Text 3' # Sol Bulletpoint Text 3
    29333a82-abf9-4d7b-904c-1f9f6be597ae: 'Sol Bulletpoint Text 2' # Sol Bulletpoint Text 2
    10796049-3cf3-4547-9fdb-16401c6d9c20: 'Dropdown Toggle' # Dropdown Toggle
    47457785-60c3-4ebd-881d-6da1f22a67e6: 'Link Destination' # Link Destination
    80446766-2d4f-4863-977e-956559c32f3e: Navigation # Navigation
    a7604adb-7e61-43a3-8714-774bfeeab423: 'sol image first' # sol image first
    ac8660a2-90e9-4864-90ca-2f340ffe007f: 'Tabs Panel1 Button Text' # Tabs Panel1 Button Text
    b073904f-64d9-4bb5-84ba-e15c5e35f456: 'Home Page' # Home Page
    b44ced1f-e6cc-452d-be3c-0ac93eae090c: 'sol button text' # sol button text
    bb0e0fd9-19d2-405c-a25b-72cf038c254e: Images # Images
    c4a611b6-b197-454c-8b52-9a6b973cfd35: 'Solutions Main Subheading' # Solutions Main Subheading
    c1907a7a-d963-46ef-992f-9b2e32c08863: 'solution matrix' # solution matrix
    c6245e3c-84a8-48c4-9111-0c523a4a29e7: 'Sol Link Url' # Sol Link Url
    d2a8a211-1516-4364-83cc-15b8e12d70b3: 'Tabs Panel1 Bulletpoint Text1' # Tabs Panel1 Bulletpoint Text1
    d53c4d5f-7703-48da-be46-b99a157059e7: 'Nav Links' # Nav Links
    d65cc449-3e95-43c1-9395-17e42961a4e4: siteSettings # siteSettings
    da5f037a-2657-4158-a31e-5b982b3132e8: 'Hero Title Text' # Hero Title Text
    e7f681f5-dd66-4868-a885-b00b6085faad: solImage # solImage
    e73abdd2-5b3e-400a-8017-810ba4c6c13b: ektask # ektask
    ecbbd1fb-b93d-4af2-8c8f-9efedfb15e8c: Link # Link
    f9f5c6bb-c399-44e1-bc1c-46a5781f4d1b: solCardSubheading # solCardSubheading
    f21d5f9b-69f0-4ef7-934a-fab500c77149: 'sol button url' # sol button url
    f95e52ca-8259-48a9-9805-c8c2922a1611: 'Sol Card Color' # Sol Card Color
    f900aa5e-c80c-4d73-876a-d45c0708f0c5: 'Solutions Main Title' # Solutions Main Title
    fa2788f2-0a27-402c-8992-ee89a969b7ba: 'Tabs Panel1 Title' # Tabs Panel1 Title
    fe86aeea-6f76-497b-b19c-38335e95ec9a: 'sol bulletpoint icon' # sol bulletpoint icon
plugins:
  colour-swatches:
    edition: standard
    enabled: true
    schemaVersion: 1.4.3
  contact-form:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
    settings:
      allowAttachments: ''
      allowedMessageFields: null
      prependSender: 'On behalf of'
      prependSubject: 'New message from ektask'
      successFlashMessage: 'Your message has been sent.'
      toEmail: test@test.com
  contact-form-honeypot:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
  image-resizer:
    edition: standard
    enabled: true
    schemaVersion: 2.0.0
  inlinesvg:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
  inventory:
    edition: standard
    enabled: true
    schemaVersion: 3.0.0
  redactor:
    edition: standard
    enabled: true
    schemaVersion: 2.3.0
  redactor-custom-styles:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
  typedlinkfield:
    edition: standard
    enabled: true
    schemaVersion: 2.0.0
  venveo-bulk-edit:
    edition: standard
    enabled: true
    schemaVersion: 4.0.0
system:
  edition: solo
  live: true
  name: ektask
  schemaVersion: 4.5.3.0
  timeZone: America/Los_Angeles
users:
  allowPublicRegistration: false
  defaultGroup: null
  photoSubpath: null
  photoVolumeUid: null
  requireEmailVerification: true
