fieldLayouts:
  90487c65-422f-4060-a206-cc27a2cc7d68:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 61282942-49f6-443d-a5e0-8d927401ede5 # Logo Strip
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 76bd9fcf-340d-4960-81ec-e2c37d60cb77
            userCondition: null
            warning: null
            width: 100
        name: 'Logo Strip Matrix'
        uid: 432cc3e9-7370-4d51-88cb-bdea8867074a
        userCondition: null
handle: logoStrip
name: 'Logo Strip'
sortOrder: 2
