fieldLayouts:
  90487c65-422f-4060-a206-cc27a2cc7d68:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 857de95a-e13a-4f40-9a44-9e5799ba9a41
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 8a4eaaa0-81c6-4004-bf82-10f11f1467a5
            userCondition: null
            warning: null
            width: 100
        name: 'Logo Strip Matrix'
        uid: 432cc3e9-7370-4d51-88cb-bdea8867074a
        userCondition: null
handle: logos
name: Logos
sortOrder: 2
