fieldLayouts:
  2d26f9ac-0866-4106-bd55-8ba79e3362b9:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: d53c4d5f-7703-48da-be46-b99a157059e7 # Nav Links
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 76686761-a96e-48c9-a634-aa2a3b08c688
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: a30d7174-a6c8-409a-b44e-52929aac20d1
        userCondition: null
handle: navigation
name: Navigation
sortOrder: 1
